Table MDD_JOB_MEDIA {
  JOB_ID NUMBER
  MEDIA_ID NUMBER
  SOURCE NUMBER
  TASK_ID NUMBER
  TASK_TYPE NUMBER
  TASK_TYPE_DESC VARCHAR2
  ARRIVE_BY DATE
  DESPATCH_FROM VARCHAR2
  DESPATCH_TO VARCHAR2
  COMPLETE_BY DATE
  TASK_STATUS NUMBER
  TASK_END DATE
  TASK_OPERATOR VARCHAR2
  TASK_TITLE_ID_FK NUMBER
  TASK_POS NUMBER
  SCHEDULE_AREA NUMBER
  CREATED_BY VARCHAR2
}

Table MDD_JOB_SCHEDULE {
  JOB_NO NUMBER
  TASK_NO NUMBER
  CLIENT_CODE VARCHAR2
  TASK_POS NUMBER
  SCHEDULE_AREA NUMBER
  PRESET_USED VARCHAR2
}

Table MDD_MEDIA_FORMATS {
  MEDIA_TYPE NUMBER
  FORMAT_ID NUMBER
  FORMAT_NAME VARCHAR2
  FORMAT_SHORT_CODE VARCHAR2
}

Table MDD_MEDIA_DISCOVERY {
}

Table MDD_ACCESS_STATUS {
  ID NUMBER [pk]
  STATUS_ID NUMBER
  ACCESS_STATUS_NAME VARCHAR2
  ACCESS_STATUS_CODE VARCHAR2
  MEDIA_ID_FK NUMBER
  DECISION_DATE DATE
  MODIFIED_DATE DATE
}

Table MDD_ACQ_CATEGORY {
  ACQ_ID_FK NUMBER [ref: > an.ACQ_ID_FK]
  CAT_ID NUMBER [pk]
  CATEGORY_NAME VARCHAR2
  CATEGORY_DESCRIPTION VARCHAR2
}

Table MDD_ACQ_CONTAINERS {
  OBJECT_DESCRIPTION VARCHAR2
  PARENT_ID NUMBER
  OBJECT_TYPE NUMBER
  MEDIA_ID2_FK VARCHAR2 [ref: > Acquisitions.MEDIA_ID2_FK]
  OBJECT_BARCODE VARCHAR2
  ACQ_EXTERNAL_REF1 VARCHAR2
  MEDIUM VARCHAR2
  SUB_MEDIUM VARCHAR2
  FORM VARCHAR2
  OBJECT_FORMAT VARCHAR2
  CONTAINER_STATUS_ID NUMBER
  CONTAINER_STATUS_DESC VARCHAR2
  ACCESSION_STATUS VARCHAR2
  QTY_RECEIVED NUMBER
  QTY_NOT_SELECTED NUMBER
  QTY_REMAINING NUMBER
  QTY_SELECTED NUMBER
  QTY_ACCESSIONED NUMBER
  QTY_AWAITING_ACCESSIONING NUMBER
  DATE_EXPECTED DATE
  DATE_RECEIVED DATE
  ARTICLE_LAST_MOVED DATE
  OBJECT_NOTES CLOB
  JOB_ID_FK NUMBER [ref: > to.JOB_ID_FK]
  TASK_ID_FK NUMBER [ref: > MDD_TASKS.TASK_ID_FK]
  ARTICLE_BARCODE VARCHAR2
  ARTICLE_FILENAME VARCHAR2
  DISPOSAL_CLASS_NO NUMBER
  ARTICLE_EXT_REF1 VARCHAR2
  ARTICLE_EXT_REF2 VARCHAR2
  CREATED_DATE DATE
}

Table MDD_ACQ_OBJECTS {
  OBJECT_ID NUMBER [pk]
  ACQ_ID NUMBER [ref: > link.ACQ_ID]
  ACQ_CONTAINER_ID_FK NUMBER [ref: > the.ACQ_CONTAINER_ID_FK]
}

Table MDD_ACQ_TYPES {
  ACQ_TYPE_ID NUMBER [pk]
  ACQ_TYPE_NAME VARCHAR2
  ACQ_TYPE_CODE VARCHAR2
  ACQ_TYPE_CATEGORY VARCHAR2
  ACQ_TYPE_ELEMENT VARCHAR2
}

Table MDD_ACQUISITIONS {
  STOCK_CHECK_ID NUMBER [ref: > list.STOCK_CHECK_ID]
  STOCK_CHECK_STATE_ID NUMBER
  STOCK_CHECK_STATE VARCHAR2
  STOCK_CHECK_BY VARCHAR2
  STOCK_CHECK_DATE DATE
  CONTAINER_LENGTH NUMBER
  LOGIN_DATE DATE
  LAST_OUT_NAME_ID_FK NUMBER [ref: > MDD_NAMES.LAST_OUT_NAME_ID_FK]
}

Table MDD_CRS_SERIES_AGENCY {
  CRS_SERIES_ID_FK NUMBER
  CRS_SERIES_NUMBER VARCHAR2
  CRS_SERIES_TITLE VARCHAR2
  ENTITY_ID_FK NUMBER [ref: > Entity.ENTITY_ID_FK]
  AGENCY_CODE VARCHAR2
  AGENCY_NAME VARCHAR2
  RELATION_TYPE NUMBER
  SERIES_TYPE VARCHAR2
}

Table MDD_ACTION_HISTORY {
  ACTION VARCHAR2
  ITEM_TYPE VARCHAR2
  USER_NAME VARCHAR2
  ITEM_ID NUMBER
  ITEM_DETAILS VARCHAR2
  PC VARCHAR2
  LAST_ACCESSED DATE
}

Table MDD_ALT_NAMES {
  NAME_ID_FK NUMBER [ref: > MDD_NAMES.NAME_ID_FK]
  ALT_NAME_ID NUMBER [pk]
  ALTERNATIVE_NAME VARCHAR2
  DATES VARCHAR2
}

Table MDD_ASPECT_RATIO {
  LEGACY_VALUE NUMBER [pk]
  AFD_CODE VARCHAR2
  DESCRIPTION NVARCHAR2
}

Table MDD_AUDIO_FROM_MIS {
  MEDIA_ID NUMBER [ref: > Media.MEDIA_ID]
  AU_NM VARCHAR2
  AU_CONT_ID VARCHAR2
  AUDIO_CONTENT NVARCHAR2
  AUDIO_CONTENT_TAG NVARCHAR2
  AU_LANG_ID VARCHAR2
  AUDIO_LANGUAGE VARCHAR2
  AUDIO_LANGUAGE_CODE VARCHAR2
  AU_MS_ID VARCHAR2
  AU_NR_ID VARCHAR2
  QC_STATUS VARCHAR2
  LANGUAGE_TAG VARCHAR2
  LANGUAGE_TAG_DESC VARCHAR2
  LANGUAGE_ISO_CODE VARCHAR2
  INTERNATIONAL_AUDIO NUMBER
}

Table MDD_AUTOPURGE_HISTORY {
  MFX_DEVICE_ID NUMBER
  MFX_DEVICE_NAME VARCHAR2
  MFX_DEVICE_CODE VARCHAR2
  MFX_DEVICE_TYPE VARCHAR2
  DEVICE_NOTES VARCHAR2
  DEVICE_LOCATION VARCHAR2
  PURGE_RULE_NAME VARCHAR2
  ACTIVE NUMBER
  LOG_ONLY NUMBER
  SCHEDULE VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
}

Table MDD_BOX_CONTAINER_TYPES {
  FORMAT_NAME VARCHAR2
  FORMAT_SHORTCODE VARCHAR2
  HEIGHT NUMBER
  WIDTH NUMBER
  DEPTH NUMBER
  WEIGHT NUMBER
  SHM NUMBER
}

Table MDD_CHANNEL_GROUPS {
  GROUP_ID NUMBER [pk]
  GROUP_CODE VARCHAR2
  GROUP_NAME VARCHAR2
  CHANNEL_CODE VARCHAR2
  ACTIVE NUMBER
}

Table MDD_CODES_ASPECT_RATIO {
  AR_ID NUMBER
  AR_NAME VARCHAR2
  AR_CODE VARCHAR2
  ACTIVE NUMBER
}

Table MDD_CODES_CHANNELS {
  CHANNEL_ID NUMBER
  CHANNEL_CODE VARCHAR2
  NAME VARCHAR2
  PARENT_CHANNEL VARCHAR2
  ACTIVE NUMBER
  PRIORITY NUMBER
}

Table MDD_CODES_CULTURAL_STATUS {
  CULTURAL_STATUS_ID NUMBER
  CULTURAL_STATUS_CODE NVARCHAR2
  CULTURAL_STATUS_NAME NVARCHAR2
  CULTURAL_STATUS_DESCRIPTION NVARCHAR2
  ACTIVE NUMBER
}

Table MDD_CODES_DEVICES {
  DEVICE_ID NUMBER
  DEVICE_NAME VARCHAR2
  DEVICE_TYPE NUMBER
  DEVICE_TYPE_NAME VARCHAR2
  DEVICE_PATH VARCHAR2
  DEVICE_REF VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
}

Table MDD_CODES_TASK_TYPES {
  TASK_TYPE_ID NUMBER [pk]
  TASK_TYPE VARCHAR2
}

Table MDD_CODES_TEC_DETAILS {
  TEC_NAME_ID NUMBER [pk]
  TEC_TYPE_ID_FK NUMBER [ref: > MDD_CODES_TEC_TYPE.TEC_TYPE_ID_FK]
  TEC_CODE VARCHAR2
  TEC_NAME VARCHAR2
  TYPE CHAR
  ACTIVE NUMBER
}

Table MDD_CODES_TEC_TYPE {
  TEC_TYPE_ID NUMBER [pk]
  TEC_TYPE_NAME VARCHAR2
  ACTIVE NUMBER
}

Table MDD_CODES_TVSTD {
  TVSTD_ID NUMBER [pk]
  NAME NVARCHAR2
  LINES NUMBER
  FPS NUMBER
  DROP_FRAME NUMBER
  CODE VARCHAR2
}

Table MDD_CONTAINER_CONDITION_TREAT {
  CONTAINER_ID NUMBER [ref: > Container.CONTAINER_ID]
  TEC_NAME_ID_FK NUMBER [ref: > Code.TEC_NAME_ID_FK]
  CONDITION_CODE VARCHAR2
  DESCRIPTION VARCHAR2
  CONDITION_TYPE VARCHAR2
  TYPE CHAR
  SEVERITY NUMBER
  DATE_ENTERED DATE
  ENTERED_BY VARCHAR2
  DEPT_ID NUMBER
  DEPT VARCHAR2
  NOTES VARCHAR2
}

Table MDD_CONTAINER_FORMATS {
  FORMAT_NAME VARCHAR2
  FORMAT_SHORTCODE VARCHAR2
  HEIGHT NUMBER
  WIDTH NUMBER
  DEPTH NUMBER
  WEIGHT NUMBER
  SHM NUMBER
}

Table MDD_CONTAINERS {
  CONTAINER_ID NUMBER [pk]
  BARCODE VARCHAR2
  EXT_ID1 VARCHAR2
  EXT_ID2 VARCHAR2
  CONTAINER_SERIES_TITLE VARCHAR2
  CONTAINER_TITLE VARCHAR2
  CONTAINER_TYPE NUMBER
  RETURN_DATE DATE
  CONTAINER_TYPE_CODE VARCHAR2
  CONTAINER_TYPE_NAME VARCHAR2
  CONTAINED_IN NUMBER [ref: > that.CONTAINED_IN]
  CONTAINER_OWNERS VARCHAR2
  FORMAT_ID NUMBER [ref: > using.FORMAT_ID]
}

Table MDD_CONTENT {
  CONTENT_ID NUMBER [pk]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  CONTENT_VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.CONTENT_VERSION_ID_FK]
  CONTENT_VERSION_ID1 VARCHAR2
  VERSION_ID1_FK VARCHAR2 [ref: > field.VERSION_ID1_FK]
  LIST_INDEX NUMBER
  TITLE VARCHAR2
  MEDIUM VARCHAR2
  SUB_MEDIUM VARCHAR2
}

Table MDD_CONTENT_PURE {
  CONTENT_ID NUMBER
  PARENT_VERSION_ID_FK NUMBER
  LIST_INDEX NUMBER
  CONTENT_TITLE VARCHAR2
}

Table MDD_CREDITS {
  CREDIT_ID NUMBER [pk]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  ENTITY_ID_FK NUMBER [ref: > to.ENTITY_ID_FK]
  NAME_ID_FK NUMBER [ref: > to.NAME_ID_FK]
  FULL_NAME VARCHAR2
  ROLE_ID NUMBER
  ROLE VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
}

Table MDD_DCTC_BBS_DELIVERY_CUSTOM {
  XML_ID NUMBER
  VERSION_ID_FK NUMBER
  BBS_NETWORK VARCHAR2
  BBS_USEPACKAGE_DATES VARCHAR2
  BBS_BUGPRESENTINSOURCE VARCHAR2
  BBS_PUBLISHTO_AOL VARCHAR2
  BBS_PUBLISHTO_BLINKX VARCHAR2
  BBS_PUBLISHTO_COMCAST VARCHAR2
  BBS_PUBLISHTO_DISH VARCHAR2
  BBS_PUBLISHTO_HULU VARCHAR2
  BBS_PUBLISHTO_MSN VARCHAR2
  BBS_PUBLISHTO_YAHOO VARCHAR2
  BBS_PUBLISHTO_YOUTUBE VARCHAR2
  BBS_CATEGORY_AOL VARCHAR2
  BBS_CATEGORY_COMCAST VARCHAR2
  BBS_CATEGORY_HULU VARCHAR2
  BBS_SERIESID_COMCAST VARCHAR2
  BBS_ISPUBLIC_YOUTUBE VARCHAR2
}

Table MDD_DCTC_BBS_MRSS_CUSTOM {
  XML_ID NUMBER
  BBS_PARTNER VARCHAR2
  BBS_NETWORK VARCHAR2
  VALID_FROM VARCHAR2
  VALID_TO VARCHAR2
  MASTER_JOB_ID VARCHAR2
  PACKAGE_ID VARCHAR2
  PAID VARCHAR2
  XML_DATA VARCHAR2
  CREATED_DATE VARCHAR2
}

Table MDD_DCTC_BBS_TITLE_CUSTOM {
  XML_ID NUMBER
  VERSION_ID_FK NUMBER
  BBS_SERIES_TITLE VARCHAR2
  BBS_SOURCE_SERIES_DESC VARCHAR2
  BBS_EPISODE_TITLE VARCHAR2
  BBS_EPISODE_SHORT_DESC VARCHAR2
  BBS_KEYWORDS VARCHAR2
  BBS_USESERIESTITLE_AOL VARCHAR2
  BBS_SERIESTITLE_AOL VARCHAR2
  BBS_USESRCSERIESDESC_AOL VARCHAR2
  BBS_SRCSERIESDESC_AOL VARCHAR2
  BBS_USEEPISODETITLE_AOL VARCHAR2
  BBS_EPISODETITLE_AOL VARCHAR2
  BBS_USEEPSHORTDESC_AOL VARCHAR2
  BBS_EPISODESHORTDESC_AOL VARCHAR2
  BBS_USEKEYWORDS_AOL VARCHAR2
  BBS_KEYWORDS_AOL VARCHAR2
  BBS_USESERIESTITLE_BLINKX VARCHAR2
  BBS_SERIESTITLE_BLINKX VARCHAR2
  BBS_USESRCSERIESDESC_BLINKX VARCHAR2
  BBS_SRCSERIESDESC_BLINKX VARCHAR2
  BBS_USEEPISODETITLE_BLINKX VARCHAR2
  BBS_EPISODETITLE_BLINKX VARCHAR2
  BBS_USEEPSHORTDESC_BLINKX VARCHAR2
  BBS_EPISODESHORTDESC_BLINKX VARCHAR2
  BBS_USEKEYWORDS_BLINKX VARCHAR2
  BBS_KEYWORDS_BLINKX VARCHAR2
  BBS_USESERIESTITLE_COMCAST VARCHAR2
  BBS_SERIESTITLE_COMCAST VARCHAR2
  BBS_USESRCSERIESDESC_COMCAS VARCHAR2
  BBS_SRCSERIESDESC_COMCAST VARCHAR2
  BBS_USEEPISODETITLE_COMCAST VARCHAR2
  BBS_EPISODETITLE_COMCAST VARCHAR2
  BBS_USEEPSHORTDESC_COMCAST VARCHAR2
  BBS_EPISODESHORTDESC_COMCAS VARCHAR2
  BBS_USESERIESTITLE_DISH VARCHAR2
  BBS_SERIESTITLE_DISH VARCHAR2
  BBS_USESRCSERIESDESC_DISH VARCHAR2
  BBS_SRCSERIESDESC_DISH VARCHAR2
  BBS_USEEPISODETITLE_DISH VARCHAR2
  BBS_EPISODETITLE_DISH VARCHAR2
  BBS_USEEPSHORTDESC_DISH VARCHAR2
  BBS_EPISODESHORTDESC_DISH VARCHAR2
  BBS_USESERIESTITLE_HULU VARCHAR2
  BBS_SERIESTITLE_HULU VARCHAR2
  BBS_USESRCSERIESDESC_HULU VARCHAR2
  BBS_SRCSERIESDESC_HULU VARCHAR2
  BBS_USEEPISODETITLE_HULU VARCHAR2
  BBS_EPISODETITLE_HULU VARCHAR2
  BBS_USEEPSHORTDESC_HULU VARCHAR2
  BBS_EPISODESHORTDESC_HULU VARCHAR2
  BBS_USEKEYWORDS_HULU VARCHAR2
  BBS_KEYWORDS_HULU VARCHAR2
  BBS_USESERIESTITLE_MSN VARCHAR2
  BBS_SERIESTITLE_MSN VARCHAR2
  BBS_USESRCSERIESDESC_MSN VARCHAR2
  BBS_SRCSERIESDESC_MSN VARCHAR2
  BBS_USEEPISODETITLE_MSN VARCHAR2
  BBS_EPISODETITLE_MSN VARCHAR2
  BBS_USEEPSHORTDESC_MSN VARCHAR2
  BBS_EPISODESHORTDESC_MSN VARCHAR2
  BBS_USEKEYWORDS_MSN VARCHAR2
  BBS_KEYWORDS_MSN VARCHAR2
  BBS_USESERIESTITLE_YAHOO VARCHAR2
  BBS_SERIESTITLE_YAHOO VARCHAR2
  BBS_USESRCSERIESDESC_YAHOO VARCHAR2
  BBS_SRCSERIESDESC_YAHOO VARCHAR2
  BBS_USEEPISODETITLE_YAHOO VARCHAR2
  BBS_EPISODETITLE_YAHOO VARCHAR2
  BBS_USEEPSHORTDESC_YAHOO VARCHAR2
  BBS_EPISODESHORTDESC_YAHOO VARCHAR2
  BBS_USEKEYWORDS_YAHOO VARCHAR2
  BBS_KEYWORDS_YAHOO VARCHAR2
  BBS_USESERIESTITLE_YOUTUBE VARCHAR2
  BBS_SERIESTITLE_YOUTUBE VARCHAR2
  BBS_USESRCSERIESDESC_YOUTUB VARCHAR2
  BBS_SRCSERIESDESC_YOUTUBE VARCHAR2
  BBS_USEEPISODETITLE_YOUTUBE VARCHAR2
  BBS_EPISODETITLE_YOUTUBE VARCHAR2
  BBS_USEEPSHORTDESC_YOUTUBE VARCHAR2
  BBS_EPISODESHORTDESC_YOUTUB VARCHAR2
  BBS_USEKEYWORDS_YOUTUBE VARCHAR2
  BBS_KEYWORDS_YOUTUBE VARCHAR2
}

Table MDD_DCTC_JOB_CUSTOM {
  JOB_ID_FK NUMBER [ref: > MDD_JOB.JOB_ID_FK]
  CHANNEL_STORAGE_LOCATION VARCHAR2
}

Table MDD_DCTC_MEDEXTENDED_CUSTOM {
  VERSION_ID_FK NUMBER
  NEW_MEDIA_TYPE VARCHAR2
  BBS_PUBLISH VARCHAR2
}

Table MDD_DCTC_MEDVERSION_CUSTOM {
  VERSION_ID_FK NUMBER [ref: > Version.VERSION_ID_FK]
  WEB_SERIES_TITLE VARCHAR2
  WEB_TITLE VARCHAR2
  WEB_SHORT_DESC VARCHAR2
  SOURCE_PAID VARCHAR2
}

Table MDD_DCTC_NLS_RUNDOWN_MEDIA {
  PACKAGE_ID NUMBER
}

Table MDD_PACKAGES {
  PACKAGE_ID NUMBER [pk]
  PACKAGE_REQ_ID_FK NUMBER
  VALID_FROM DATE
  VALID_TO DATE
  VERSION_ID_FK NUMBER [ref: > version.VERSION_ID_FK]
  PREP_JOB_ID NUMBER
  PREP_JOB_STATUS_ID NUMBER
  PREP_JOB_STATUS VARCHAR2
  JOB_ID_FK NUMBER [ref: > job.JOB_ID_FK]
  PACKAGE_JOB_NO VARCHAR2
  PACKAGE_JOB_STATUS_ID NUMBER
  PACKAGE_JOB_STATUS VARCHAR2
  EXTERNAL_REF VARCHAR2
  ASSET_ID_CHOICE VARCHAR2
  USER_ASSET_ID VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  CREATED_BY_EMAIL VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  DELETED NUMBER
}

Table MDD_DCTC_NLS_VUBIQUITY_PLANNER {
  PACKAGE_ID_FK NUMBER
  PROVIDER VARCHAR2
  PROVIDER_ID VARCHAR2
  ASSET_ID VARCHAR2
  PACKAGE_ASSET_ID VARCHAR2
  TITLE_ASSET_ID VARCHAR2
  MOVIE_ASSET_ID VARCHAR2
  POSTER_ART_ASSET_ID VARCHAR2
  BOX_COVER_ASSET_ID VARCHAR2
  PROVIDER_CONTENT_TIER VARCHAR2
  VIDEO_FORMAT VARCHAR2
  TITLE VARCHAR2
  LICENSING_WINDOW_START VARCHAR2
  LICENSING_WINDOW_END VARCHAR2
  MOVIE_RUN_TIME VARCHAR2
  MOVIE_FILE_NAME VARCHAR2
  POSTER_ART_FILE_NAME VARCHAR2
  BOX_COVER_FILE_NAME VARCHAR2
  MANIFEST_ID VARCHAR2
}

Table MDD_DCTC_PACKAGE_CUSTOM {
  PACKAGE_ID_FK NUMBER
  USNETS_DISTRIBUTION_CHANNEL VARCHAR2
  KEYWORDS VARCHAR2
  VIDEO_CATEGORY VARCHAR2
}

Table MDD_DCTC_SERIES_CUSTOM {
  PARENT_SERIES_ID_FK NUMBER [ref: > PARENT_SERIES_ID_FK.PARENT_SERIES_ID_FK]
  PDS_SERIES_NAME VARCHAR2
}

Table MDD_DIGITAL_FILE_LINKS {
  MEDIA_ID_FK NUMBER
  DIGITAL_FILE_ID_FK NUMBER
  MEDIA_ITEM_INDEX NUMBER
  DIGITAL_FILE_INDEX NUMBER
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
}

Table MDD_DIGITAL_FILES {
  DFILE_ID NUMBER [pk]
  DTYPE_ID NUMBER
  DFILE_TYPE VARCHAR2
  PATH VARCHAR2
  FILENAME VARCHAR2
  FILE_EXTENSION VARCHAR2
  DEVICE_ID NUMBER [ref: > digital.DEVICE_ID]
  DEVICE_NAME VARCHAR2
  FILESIZE NUMBER
  CREATED DATE
  CREATED_BY VARCHAR2
  MODIFIED DATE
  MODIFIED_BY VARCHAR2
  SOM_FRAMES NUMBER
  SOM_TIMECODE VARCHAR2
  EOM_FRAMES NUMBER
  EOM_TIMECODE VARCHAR2
  DURATION_FRAMES NUMBER
  DURATION_TIMECODE VARCHAR2
  TV_STANDARD_ID NUMBER [ref: > in.TV_STANDARD_ID]
  TV_STANDARD_NAME NVARCHAR2
  MEDIA_FILE_TYPE_ID NUMBER [ref: > in.MEDIA_FILE_TYPE_ID]
  MEDIA_FILE_TYPE_NAME VARCHAR2
  EXT_REF1 VARCHAR2
  EXT_REF2 VARCHAR2
  ORIGINAL_FILENAME VARCHAR2
  DFILE_LINK_GUID VARCHAR2
}

Table MDD_DISPOSAL_RECORDS {
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  DISPOSAL_CLASS_ID NUMBER
  DISPOSAL_CLASS NUMBER
  DISPOSAL_CLASS_DESCRIPTION VARCHAR2
  DISPOSAL_STATUS_ID NUMBER
  DISPOSAL_STATUS VARCHAR2
  DISPOSAL_DUE_DATE DATE
  DISPOSAL_ACTION VARCHAR2
  MODIFIED_BY VARCHAR2
  MODIFIED_DT DATE
}

Table MDD_ENTITY_NATIONALITIES {
  ENTITY_ID NUMBER [ref: > MDD_ENTITIES.ENTITY_ID]
  NATIONALITY VARCHAR2
}

Table MDD_GROUP_MEDIA {
  TAG_ID NUMBER [pk]
  GROUP_ID_FK NUMBER [ref: > MDD_GROUPS.GROUP_ID_FK]
  ITEM_TYPE NUMBER
  ITEM_ID NUMBER [ref: > of.ITEM_ID]
  TITLE_ID_FK NUMBER [ref: > MDD_TITLES.TITLE_ID_FK]
  CONTAINER_ID_FK NUMBER [ref: > MDD_CONTAINERS.CONTAINER_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  JOB_ID_FK NUMBER
  LOAN_ITEM_ID_FK NUMBER [ref: > MDD_JOB.LOAN_ITEM_ID_FK]
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  STATUS NUMBER
  STOCK_CHECK_STATUS_ID NUMBER
  STOCK_CHECK_STATUS VARCHAR2
  STOCK_CHECK_DATE DATE
  STOCK_CHECK_USER VARCHAR2
}

Table MDD_GROUPS {
  GROUP_ID NUMBER [pk]
  PARENT_ID NUMBER [ref: > one.PARENT_ID]
  GROUP_NAME VARCHAR2
  GROUP_DESCRIPTION VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  IMPORTED_DATE DATE
  REFRESHED_DATE DATE
  GROUP_TYPE_ID NUMBER
  LIST_COMPLETED NUMBER
  LIST_COMPLETED_DATE DATE
  LIST_COMPLETED_BY VARCHAR2
}

Table MDD_HISTORY {
  HISTORY_ID NUMBER [pk]
  HISTORY_TYPE_ID NUMBER
  HISTORY_TYPE VARCHAR2
  HISTORY_TEXT VARCHAR2
  TASK_ID_FK NUMBER [ref: > MDD_TASKS.TASK_ID_FK]
  INTEGER1_HEADER VARCHAR2
  PARENT_ID NUMBER [ref: > Media.PARENT_ID]
  PARENT_TYPE_ID NUMBER
  INTEGER_VALUE1 NUMBER
  QC_STATUS VARCHAR2 [pk]
  INTEGER_VALUE2 NUMBER
  STRING_VALUE1 VARCHAR2
  STRING_VALUE2 VARCHAR2
  NOTES VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
}

Table MDD_HISTORY_EQUIPMENT {
  HISTORY_ID_FK NUMBER [ref: > data.HISTORY_ID_FK]
  EQUIPMENT_ORDER NUMBER
  EQUIPMENT_NAME VARCHAR2
  EQUIPMENT_ID_FK VARCHAR2 [ref: > key.EQUIPMENT_ID_FK]
}

Table MDD_IBMS_VERSIONS {
  ID NUMBER
  HOUSE_NUMBER VARCHAR2
  FILE_REF VARCHAR2
}

Table MDD_JOB {
  JOB_ID NUMBER [pk]
  JOB_NO VARCHAR2
  CLIENT_REF VARCHAR2
  JOB_CREATE_DATE DATE
  JOB_CREATED_BY VARCHAR2
  JOB_COMPLETE_BY DATE
  JOB_COMPLETED_DATE DATE
  JOB_COMPLETED_DMY VARCHAR2
  JOB_COMPLETED_MY VARCHAR2
  JOB_COMPLETED_M_NUM NUMBER
  JOB_COMPLETED_YEAR VARCHAR2
  OWNERS VARCHAR2
  JOB_NOTES VARCHAR2
  PRESET_ID NUMBER
  PRESET_USED VARCHAR2
  PRESET_DESC VARCHAR2
  PRESET_ACTIVE NUMBER
  JOB_STATUS_ID NUMBER
  JOB_STATUS VARCHAR2
  FAILURE_RESOLVED NUMBER
  JOB_REQUEST_REFERENCE VARCHAR2
  PARENT_JOB NUMBER
}

Table MDD_LANG_DATA {
  ID NUMBER [pk]
  LANGUAGE_SHORTCODE VARCHAR2
  LANGUAGE_NAME VARCHAR2
  ISO_CODE VARCHAR2
}

Table MDD_LOAN_HEADER {
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  CONTAINER_ID_FK NUMBER
  MEDIA_ID1 VARCHAR2
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  BARCODE VARCHAR2
  SERIES_TITLE VARCHAR2
  EPISODE_TITLE VARCHAR2
  NEXT_TX_DATE DATE
  REQUIRED_DATE DATE
  RETURN_DATE DATE
  DATE_LOANED DATE
  DATE_RETURNED DATE
  STATUS VARCHAR2
  ITEM_TYPE VARCHAR2
}

Table MDD_LOAN_ITEMS {
  LOAN_ITEM_ID NUMBER
  LOAN_NO NUMBER [ref: > in.LOAN_NO]
}

Table MDD_LOCATION_USE {
  LOC NUMBER
  ACTUAL_COUNT NUMBER
  ACTUAL_VOLUME_USED NUMBER
  ACTUAL_LENGTH_USED NUMBER
  LAST_HOME_VOLUME_USED NUMBER
  LAST_HOME_COUNT NUMBER
  LAST_HOME_LENGTH_USED NUMBER
  SUGGESTED_COUNT NUMBER
  SUGGESTED_VOLUME_USED NUMBER
  SUGGESTED_LENGTH_USED NUMBER
  TOTAL_COUNT NUMBER
  TOTAL_VOLUME_USED NUMBER
  TOTAL_LENGTH_USED NUMBER
}

Table MDD_LOCATIONS {
  LOCATION_ID NUMBER [pk]
  NAME VARCHAR2
  SHORT_CODE VARCHAR2
  PARENT_ID_FK NUMBER [ref: > (MDD_LOCATIONS).PARENT_ID_FK]
  LOCATION_TYPE VARCHAR2
  FULL_LOCATION_NAME VARCHAR2
  FULL_LOCATION_CODE VARCHAR2
  LOCATION_BARCODE NUMBER
  CREATED DATE
  CREATED_BY VARCHAR2
  MODIFIED DATE
  MODIFIED_BY VARCHAR2
  AREA_EMAIL VARCHAR2
  ACCLIMATISATION_PERIOD NUMBER
  TEMPERATURE_CLASSIFICATION VARCHAR2
  AIR_CONDITIONING VARCHAR2
  HUMIDITY NUMBER
  HOME_LONG_TERM VARCHAR2
  BOOKING_READY VARCHAR2
  BOOKING_RETURN VARCHAR2
  CONFIGURED_STORAGE VARCHAR2
  LOCATION_FULL VARCHAR2
  RETURN_TO_HOME VARCHAR2
  PREFERRED VARCHAR2
  CUSTOM_FLAGS VARCHAR2
  SHELF_WIDTH NUMBER
  SHELF_HEIGHT NUMBER
  SHELF_DEPTH NUMBER
  PRESET_NAME VARCHAR2
  CAPACITY_CALCULATION_ID NUMBER
  CAPACITY_CALCULATION VARCHAR2
  MAX_ITEMS NUMBER
  LOC_DELETED NUMBER
  LOC_DELETED_BY VARCHAR2
  LOC_DELETED_DT DATE
}

Table MDD_MEDIA {
  MEDIA_ID NUMBER [pk]
  U_TO_TXD DATE
  U_FRM_TXD DATE
  SERIES_ID_FK NUMBER [ref: > MDD_TITLES.SERIES_ID_FK]
  TITLE_ID_FK NUMBER [ref: > MDD_TITLES.TITLE_ID_FK]
  MASTER_VERSION_ID_FK NUMBER [ref: > immediate.MASTER_VERSION_ID_FK]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  ACQ_ID_FK NUMBER [ref: > MDD_ACQUISITIONS.ACQ_ID_FK]
  MEDIA_TITLE VARCHAR2
  MEDIA_SERIES_TITLE VARCHAR2
  MEDIA_ID1 VARCHAR2
  COMPONENT_NO VARCHAR2
  CARRIER_NO VARCHAR2
  TV_NUM NUMBER
  MEDIA_ID2 VARCHAR2
  ITEM_TYPE_ID NUMBER [ref: > MDD_MEDIA_ITEM_TYPES.ITEM_TYPE_ID]
  ITEM_TYPE VARCHAR2
  ITEM_SUB_TYPE_ID NUMBER
  ITEM_SUB_TYPE VARCHAR2
  ITEM_FORMAT_ID NUMBER
  ITEM_FORMAT VARCHAR2
  NFSA_ITEM_TYPE VARCHAR2
  OWNERS VARCHAR2
  DESCRIPTION VARCHAR2
  SERIES_NAME VARCHAR2
  SERIES_NO NUMBER
  SERIES_EPISODE_NO NUMBER
  SERIES_ID1 VARCHAR2
  SERIES_ID2 VARCHAR2
  PROG_ID1 VARCHAR2
  PROG_ID2 VARCHAR2
  HOUSE_NUMBER VARCHAR2
  VERSION_NAME VARCHAR2
  VERSION_ID1 VARCHAR2
  VERSION_ID2 VARCHAR2
  PRODUCTION_YEAR NUMBER
  SOM NUMBER
  EOM NUMBER
  SOM_TIMECODE VARCHAR2
  EOM_TIMECODE VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  CREATED_BY_DEPT_ID NUMBER
  CREATED_BY_DEPT VARCHAR2
  CREATED_BY_EMAIL VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  STATUS_ID NUMBER
  STATUS_DESC NVARCHAR2
  RESTRICTION_STATUS VARCHAR2
  USAGE_ID NUMBER
  USAGE_TYPE VARCHAR2
  USAGE_SHORTCODE VARCHAR2
  MEDIA_STATUS_ID NUMBER
  MEDIA_STATUS NVARCHAR2
  ATTACHMENT_FILENAMES CLOB
  URL_REFERENCES CLOB
  PROGRAM_DURATION NUMBER
  DURATION_MILLISECONDS NUMBER
  DURATION_SECONDS NUMBER
  CALCULATED_DURATION NUMBER
  DURATION_TIMECODE VARCHAR2
  SLOT_DUR NUMBER
  ASSESS_STATUS VARCHAR2
  ASSESS_DATE DATE
  TV_STD_ID NUMBER
  TV_STD NVARCHAR2
  ASPECT_RATIO_ID NUMBER
  ASPECT_RATIO VARCHAR2
  AFD_ID NUMBER
  AFD_DESC NVARCHAR2
  ASPECT_RATIO_LEGACY_ID NUMBER
  ASPECT_RATIO_LEGACY NVARCHAR2
  AFD_CODE VARCHAR2
  LANGUAGE_ID NUMBER
  LANGUAGE VARCHAR2
  FLAG_1 NUMBER
  FLAG_2 NUMBER
  FLAG_3 NUMBER
  FLAG_4 NUMBER
  FLAG_5 NUMBER
  FLAG_6 NUMBER
  FLAG_7 NUMBER
  FLAG_8 NUMBER
  FLAG_9 NUMBER
  FLAG_10 NUMBER
  FLAG_11 NUMBER
  FLAG_12 NUMBER
  FLAG_13 NUMBER
  FLAG_14 NUMBER
  FLAG_15 NUMBER
  FLAG_16 NUMBER
  CLOSEDCAPTION VARCHAR2
  SUBTITLES VARCHAR2
  COLOR NUMBER
  COLOUR_DESC NVARCHAR2
  AU_TRACKS_NUM NUMBER
  AU_TRACKS_LANGUAGES VARCHAR2
  AU_TRACKS_CONT VARCHAR2
  AU_TRACKS_MS VARCHAR2
  AU_TRACKS_MODE VARCHAR2
  OS_DIR VARCHAR2
  OS_FILENAME VARCHAR2
  DIGITAL_FILENAME VARCHAR2
  PATH VARCHAR2
  FILE_SIZE NUMBER
  MEDIA_LOCATION VARCHAR2
  DEVICE_ID NUMBER
  PARENT_ID NUMBER
  FILE_NAME VARCHAR2
  FILE_TYPE VARCHAR2
  FILE_EXTENSION VARCHAR2
  FILENAME_NO_EXTENSION VARCHAR2
  MEDIA_FORMAT_ID NUMBER
  MEDIA_TYPE NUMBER
  MEDIA_TYPE_DESC VARCHAR2
  MEDIA_FORMAT_NAME VARCHAR2
  ARCHIVED NUMBER
  DELETED NUMBER
  MI_DELETED NUMBER
  DELETED_DATE DATE
  FULL_TECHCODE VARCHAR2
  MEDIA_FORMAT_CODE VARCHAR2
  FLAG_SUPPLIED NUMBER
  FLAG_CREATED NUMBER
  ORIGIN VARCHAR2
  A_GRADE NUMBER
  V_GRADE NUMBER
  CRS_SERIES_ID NUMBER
  CRS_SERIES_NO VARCHAR2
  CRS_SERIES_TITLE VARCHAR2
  SUITABLE_VOEC NUMBER
  MEDIA_LINK_ID_FK NUMBER
  DIVA_CATEGORY VARCHAR2
  DIVA_MEDIA_GROUP VARCHAR2
  FPS NVARCHAR2
  CHECKSUM VARCHAR2
  LAST_TX_DATE DATE
  ITEM_TYPE_SHORTCODE VARCHAR2
  ASSISTED_ASSESS_STATUS VARCHAR2
  MEDIA_ID3 VARCHAR2
  MEDIA_SHELL VARCHAR2
  IS_ORIGINAL_AUDIO VARCHAR2
}

Table MDD_MEDIA_AUDIO {
  AUDIO_ID NUMBER
  MEDIA_ID NUMBER [ref: > MDD_MEDIA.MEDIA_ID]
  TRACK_NUMBER NVARCHAR2
  AU_NM NVARCHAR2
  AUDIO_NM NVARCHAR2
  AU_CONT_ID NUMBER
  AUDIO_CONTENT NVARCHAR2
  AUDIO_CONTENT_TAG NVARCHAR2
  AU_LANG_ID NUMBER
  AUDIO_LANGUAGE VARCHAR2
  AUDIO_LANGUAGE_CODE VARCHAR2
  AU_MS_ID NUMBER
  AUDIO_MS NVARCHAR2
  AUDIO_MS_CODE NVARCHAR2
  AU_NR_ID NUMBER
  AUDIO_NR NUMBER
  QC_STATUS NUMBER
  LANGUAGE_TAG NUMBER
  LANGUAGE_TAG_DESC NVARCHAR2
  LANGUAGE_ISO_CODE VARCHAR2
  INGEST_SELECTED NUMBER
  PRIMARY_AUDIO NUMBER
  INTERNATIONAL_AUDIO NUMBER
  AUDIO_QC_PASS NUMBER
  AUDIO_QC_FAIL NUMBER
  TAG_MATCH NUMBER
  STACKED NUMBER
  STACKED_DATE DATE
  TRACK_RENAMED NUMBER
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  KHZ VARCHAR2
  PEAK VARCHAR2
  AVG VARCHAR2
  DIP VARCHAR2
  LM100_SHORT VARCHAR2
  LM100_LONG VARCHAR2
}

Table MDD_MEDIA_AUDIO_EXTRAS {
  MEDIA_ID_FK NUMBER
  TASK_ID_FK NUMBER
  TRACK_INDEX NUMBER
  KHZ VARCHAR2
  PEAK VARCHAR2
  AVG VARCHAR2
  DIP VARCHAR2
  LM100_SHORT VARCHAR2
  LM100_LONG VARCHAR2
}

Table MDD_MEDIA_AUDIO_NS {
  MEDIA_ID NUMBER [ref: > MDD_MEDIA.MEDIA_ID]
  AU_NM NVARCHAR2
  AU_CONT_ID NUMBER
  AUDIO_CONTENT NVARCHAR2
  AUDIO_CONTENT_TAG NVARCHAR2
  AU_LANG_ID NUMBER
  AUDIO_LANGUAGE VARCHAR2
  AUDIO_LANGUAGE_CODE VARCHAR2
  AU_MS_ID NUMBER
  AUDIO_MS NVARCHAR2
  AUDIO_MS_CODE NVARCHAR2
  AU_NR_ID NUMBER
  QC_STATUS NUMBER
  LANGUAGE_TAG NUMBER
  LANGUAGE_TAG_DESC NVARCHAR2
  LANGUAGE_ISO_CODE VARCHAR2
  INGEST_SELECTED NUMBER
  PRIMARY_AUDIO NUMBER
  INTERNATIONAL_AUDIO NUMBER
  AUDIO_QC_PASS NUMBER
  AUDIO_QC_FAIL NUMBER
  TAG_MATCH NUMBER
  STACKED NUMBER
  STACKED_DATE DATE
  TRACK_RENAMED NUMBER
}

Table MDD_MEDIA_CHANNELS {
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  CHANNEL_ID_FK NUMBER [ref: > MDD_CODES_CHANNELS.CHANNEL_ID_FK]
  CHANNEL_CODE VARCHAR2
}

Table MDD_MEDIA_CONTNRS_LNK {
  MEDIA_ID NUMBER [ref: > MDD_MEDIA.MEDIA_ID]
  CONTAINER_ID NUMBER [ref: > MDD_CONTAINERS.CONTAINER_ID]
  SCAN_LOCATION VARCHAR2
}

Table MDD_MEDIA_COPY_HISTORY {
  ID NUMBER [pk]
  MEDIA_ID_FK NUMBER
  SOURCE_MEDIA_ID_FK NUMBER
  SOURCE_VERSION_ID_FK NUMBER
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  ENTERED_DATE DATE
  ENTERED_BY VARCHAR2
  CUT NUMBER
  SIDE VARCHAR2
}

Table MDD_MEDIA_CUSTOM_STATUS {
  MEDIA_ID_FK NUMBER [ref: > item.MEDIA_ID_FK]
  STATUS_ID NUMBER
  MEDIA_STATUS VARCHAR2
  STATUS_TYPE_ID NUMBER
  MEDIA_STATUS_TYPE VARCHAR2
}

Table MDD_MEDIA_FAULTS {
  FAULT_ID NUMBER [pk]
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  JOB_ID_FK NUMBER [ref: > MDD_JOB.JOB_ID_FK]
  TASK_ID_FK NUMBER [ref: > MDD_TASKS.TASK_ID_FK]
  FAULT VARCHAR2
  FAULT_TYPE VARCHAR2
  FAULT_INDEX NUMBER
  TIMECODE_IN VARCHAR2
  TIMECODE_OUT VARCHAR2
  SEVERITY VARCHAR2
  DURATION VARCHAR2
  SECTORS VARCHAR2
  NOTES VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  FIXED VARCHAR2
}

Table MDD_MEDIA_FAULTS_NS {
}

Table MDD_MEDIA_FORMAT_TECH_CODES {
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  FORMAT_TECH_CODE_SUB_TYPE VARCHAR2
  FORMAT_TECH_CODE_VALUE VARCHAR2
}

Table MDD_MEDIA_ITEM_TYPES {
  ID NUMBER [pk]
  ITEM_TYPE_NAME VARCHAR2
  ITEM_TYPE_DESCRIPTION VARCHAR2
  ITEM_TYPE_SHORTCODE VARCHAR2
  ITEM_TYPE_SHORTNAME VARCHAR2
  ITEM_GROUP VARCHAR2
  ITEM_GROUP_ID NUMBER
}

Table MDD_MEDIA_LOCATORS {
  LOCATOR_ID NUMBER [pk]
  MEDIA_ID_FK NUMBER [ref: > item.MEDIA_ID_FK]
  LINKING_GUID VARCHAR2
  LOCATOR_TYPE VARCHAR2
  IN_TC_TEXT VARCHAR2
  OUT_TC_TEXT VARCHAR2
  NOTES VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
}

Table MDD_MEDIA_METADATA {
  MEDIA_ID NUMBER
  SERIES_ID_FK NUMBER
  TITLE_ID_FK NUMBER
  MASTER_VERSION_ID_FK NUMBER
  VERSION_ID_FK NUMBER
  MEDIA_TITLE VARCHAR2
  MEDIA_SERIES_TITLE VARCHAR2
  MEDIA_ID1 VARCHAR2
  MEDIA_ID2 VARCHAR2
  ITEM_TYPE_ID NUMBER
  ITEM_TYPE VARCHAR2
  ITEM_SUB_TYPE_ID NUMBER
  ITEM_SUB_TYPE VARCHAR2
  ITEM_TYPE_SHORTCODE VARCHAR2
  ITEM_FORMAT_ID NUMBER
  ITEM_FORMAT VARCHAR2
  OWNERS VARCHAR2
  DESCRIPTION VARCHAR2
  SERIES_NAME VARCHAR2
  SERIES_NO NUMBER
  SERIES_EPISODE_NO NUMBER
  SERIES_ID1 VARCHAR2
  SERIES_ID2 VARCHAR2
  PROG_ID1 VARCHAR2
  PROG_ID2 VARCHAR2
  HOUSE_NUMBER VARCHAR2
  VERSION_NAME VARCHAR2
  VERSION_ID1 VARCHAR2
  VERSION_ID2 VARCHAR2
  PRODUCTION_YEAR NUMBER
  SOM NUMBER
  EOM NUMBER
  SOM_TIMECODE VARCHAR2
  EOM_TIMECODE VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  USAGE_ID NUMBER
  USAGE_TYPE VARCHAR2
  PROGRAM_DURATION NUMBER
  DURATION_MILLISECONDS NUMBER
  DURATION_SECONDS NUMBER
  CALCULATED_DURATION NUMBER
  DURATION_TIMECODE VARCHAR2
  ASSESS_STATUS VARCHAR2
  TV_STD_ID NUMBER
  TV_STD NVARCHAR2
  ASPECT_RATIO_ID NUMBER
  ASPECT_RATIO VARCHAR2
  AFD_ID NUMBER
  AFD_DESC NVARCHAR2
  LANGUAGE_ID NUMBER
  LANGUAGE VARCHAR2
  CLOSEDCAPTION VARCHAR2
  SUBTITLES VARCHAR2
  COLOR NUMBER
  COLOUR_DESC NVARCHAR2
  MEDIA_LOCATION VARCHAR2
  PARENT_ID NUMBER
  MEDIA_FORMAT VARCHAR2
  FILE_TYPE VARCHAR2
  MEDIA_FORMAT_ID NUMBER
  MEDIA_TYPE NUMBER
  MEDIA_TYPE_DESC VARCHAR2
  MEDIA_FORMAT_FULL VARCHAR2
  ARCHIVED NUMBER
  DELETED NUMBER
  MI_DELETED NUMBER
  DELETED_DATE DATE
  MEDIA_FORMAT_CODE VARCHAR2
  FLAG_SUPPLIED NUMBER
  FLAG_CREATED NUMBER
  ORIGIN VARCHAR2
  A_GRADE NUMBER
  V_GRADE NUMBER
  SUITABLE_VOEC NUMBER
  MEDIA_LINK_ID_FK NUMBER
  MI_LINK_GUID VARCHAR2
  DFILE_LINK_GUID VARCHAR2
  DIVA_CATEGORY VARCHAR2
  DIVA_MEDIA_GROUP VARCHAR2
  FPS NVARCHAR2
  CHECKSUM VARCHAR2
  LAST_TX_DATE DATE
  ASSISTED_ASSESS_STATUS VARCHAR2
  MEDIA_ID3 VARCHAR2
  MEDIA_SHELL VARCHAR2
  IS_ORIGINAL_AUDIO VARCHAR2
}

Table MDD_MEDIA_RIGHTS {
  RIGHTS_ID NUMBER [pk]
  RIGHTS_HOLDER NUMBER
  CONTACT VARCHAR2
  AGREEMENT_DATE DATE
  FILE_REF VARCHAR2
  CREATED DATE
  CREATED_BY VARCHAR2
  MEDIA_ID NUMBER
  PERMISSION_TYPE NUMBER
  PERM_TYPE_DESC VARCHAR2
  START_DATE DATE
  END_DATE DATE
  GEOGRAPHICAL_COVERAGE NUMBER
  GEO_COVERAGE_DESC VARCHAR2
  PROJECT_CODE VARCHAR2
  PROJECT_CODE_DESC VARCHAR2
}

Table MDD_MEDIA_SEGMENTS {
  SEGMENT_ID NUMBER [pk]
  MEDIA_ID NUMBER [ref: > MDD_MEDIA.MEDIA_ID]
  SEQUENCE_NO NUMBER
  SEGMENT_NO NUMBER
  PART_NO NUMBER
  SEGMENT_TYPE NUMBER
  PART_TYPE_ID NUMBER
  SEGMENT_TYPE_DESC NVARCHAR2
  SEGMENT_TYPE_SHORT NVARCHAR2
  SEGMENT_TITLE VARCHAR2
  SOM_FRAMES NUMBER
  SOM VARCHAR2
  EOM_FRAMES NUMBER
  EOM VARCHAR2
  DURATION_FRAMES NUMBER
  DUR VARCHAR2
  USE_IN_DUR_CALC NUMBER
  TX_PART NUMBER
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
}

Table MDD_MEDIA_SIMPLE {
  MEDIA_ID NUMBER [pk]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  VERSION_NAME VARCHAR2
  VERSION_ID1 VARCHAR2
  DIGITAL_FILENAME VARCHAR2
  PATH VARCHAR2
  DEVICE_ID NUMBER
  MEDIA_TYPE NUMBER
  MEDIA_TYPE_DESC VARCHAR2
  MEDIA_FORMAT_NAME VARCHAR2
  DELETED NUMBER
}

Table MDD_MEDIA_USAGE_TYPES {
  ID NUMBER [pk]
  USAGE_NAME VARCHAR2
  USAGE_DESCRIPTION VARCHAR2
  USAGE_SHORTCODE VARCHAR2
}

Table MDD_MEDIA_VALUATION_MEDIA {
  MEDIA_FK NUMBER
  MEDIA_ID1 VARCHAR2
  VALUATION_PERIOD_FK NUMBER
  VALUATION_PERIOD VARCHAR2
  USAGE_GROUP_FK NUMBER
  USAGE_GROUP VARCHAR2
  ORIGIN_FK NUMBER
  ORIGIN VARCHAR2
  ACQ_TYPE_ELEMENT_FK NUMBER
  ACQ_TYPE_ELEMENT VARCHAR2
  ITEM_FORMAT_FK NUMBER
  ITEM_FORMAT VARCHAR2
  ITEM_TYPE_FK NUMBER
  ITEM_TYPE VARCHAR2
  VALUATION_FK VARCHAR2
  TECH_CODE VARCHAR2
  VALUE_BY_BITWISE NUMBER
  CARRIERS NUMBER
  FILE_SIZE_BYTES NUMBER
  CREATED_DT DATE
}

Table MDD_MEDIA_WITH_VIRTUAL {
  MEDIA_ID NUMBER
  SERIES_ID_FK NUMBER
  TITLE_ID_FK NUMBER
  MASTER_VERSION_ID_FK NUMBER
  VERSION_ID_FK NUMBER
  ACQ_ID_FK NUMBER
  MEDIA_TITLE VARCHAR2
  MEDIA_SERIES_TITLE VARCHAR2
  MEDIA_ID1 VARCHAR2
  COMPONENT_NO VARCHAR2
  CARRIER_NO VARCHAR2
  MEDIA_ID2 VARCHAR2
  ITEM_TYPE_ID NUMBER
  ITEM_TYPE VARCHAR2
  ITEM_FORMAT_ID NUMBER
  ITEM_FORMAT VARCHAR2
  NFSA_ITEM_TYPE VARCHAR2
  OWNERS VARCHAR2
  DESCRIPTION VARCHAR2
  SERIES_NAME VARCHAR2
  SERIES_NO NUMBER
  SERIES_EPISODE_NO NUMBER
  SERIES_ID1 VARCHAR2
  SERIES_ID2 VARCHAR2
  PROG_ID1 VARCHAR2
  PROG_ID2 VARCHAR2
  HOUSE_NUMBER VARCHAR2
  VERSION_NAME VARCHAR2
  VERSION_ID1 VARCHAR2
  VERSION_ID2 VARCHAR2
  PRODUCTION_YEAR NUMBER
  SOM NUMBER
  EOM NUMBER
  SOM_TIMECODE VARCHAR2
  EOM_TIMECODE VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  CREATED_BY_DEPT_ID NUMBER
  CREATED_BY_DEPT VARCHAR2
  CREATED_BY_EMAIL VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  STATUS_ID NUMBER
  STATUS_DESC NVARCHAR2
  RESTRICTION_STATUS VARCHAR2
  USAGE_ID NUMBER
  USAGE_TYPE VARCHAR2
  USAGE_SHORTCODE VARCHAR2
  PROGRAM_DURATION NUMBER
  DURATION_MILLISECONDS NUMBER
  CALCULATED_DURATION NUMBER
  ASSESS_STATUS VARCHAR2
  TV_STD_ID NUMBER
  TV_STD NVARCHAR2
  ASPECT_RATIO_ID NUMBER
  ASPECT_RATIO VARCHAR2
  AFD_ID NUMBER
  AFD_DESC NVARCHAR2
  ASPECT_RATIO_LEGACY_ID NUMBER
  ASPECT_RATIO_LEGACY NVARCHAR2
  AFD_CODE VARCHAR2
  LANGUAGE_ID NUMBER
  LANGUAGE VARCHAR2
  FLAG_1 NUMBER
  FLAG_2 NUMBER
  FLAG_3 NUMBER
  FLAG_4 NUMBER
  FLAG_5 NUMBER
  FLAG_6 NUMBER
  FLAG_7 NUMBER
  FLAG_8 NUMBER
  FLAG_9 NUMBER
  FLAG_10 NUMBER
  FLAG_11 NUMBER
  FLAG_12 NUMBER
  FLAG_13 NUMBER
  FLAG_14 NUMBER
  FLAG_15 NUMBER
  FLAG_16 NUMBER
  CLOSEDCAPTION VARCHAR2
  SUBTITLES VARCHAR2
  COLOR NUMBER
  COLOUR_DESC NVARCHAR2
  AU_TRACKS_NUM NUMBER
  AU_TRACKS_LANGUAGES VARCHAR2
  AU_TRACKS_CONT VARCHAR2
  AU_TRACKS_MS VARCHAR2
  AU_TRACKS_MODE VARCHAR2
  OS_DIR VARCHAR2
  OS_FILENAME VARCHAR2
  PATH VARCHAR2
  FILE_SIZE NUMBER
  MEDIA_LOCATION VARCHAR2
  PARENT_ID NUMBER
  FILE_NAME VARCHAR2
  FILE_TYPE VARCHAR2
  FILE_EXTENSION VARCHAR2
  MEDIA_FORMAT_ID NUMBER
  MEDIA_TYPE NUMBER
  MEDIA_TYPE_DESC VARCHAR2
  MEDIA_FORMAT_NAME VARCHAR2
  ARCHIVED NUMBER
  DELETED NUMBER
  MI_DELETED NUMBER
  DELETED_DATE DATE
  FULL_TECHCODE VARCHAR2
  MEDIA_FORMAT_CODE VARCHAR2
  FLAG_SUPPLIED NUMBER
  FLAG_CREATED NUMBER
  ORIGIN VARCHAR2
  A_GRADE NUMBER
  V_GRADE NUMBER
  CRS_SERIES_ID NUMBER
  CRS_SERIES_NO VARCHAR2
  CRS_SERIES_TITLE VARCHAR2
  SUITABLE_VOEC NUMBER
  MEDIA_LINK_ID_FK NUMBER
  DIVA_CATEGORY VARCHAR2
  DIVA_MEDIA_GROUP VARCHAR2
}

Table MDD_MIS_AUDIO {
  MIS_ID NUMBER
  TASK_ID_FK NUMBER
  TRACK_INDEX NUMBER
  AU_NM_ID VARCHAR2
  AU_CONT_ID VARCHAR2
  AU_LANG_ID VARCHAR2
  AU_MS_ID VARCHAR2
  AU_NR_ID VARCHAR2
  KHZ VARCHAR2
  PEAK VARCHAR2
  AVG VARCHAR2
  DIP VARCHAR2
  LM100_SHORT VARCHAR2
  LM100_LONG VARCHAR2
  LANGUAGE_TAG VARCHAR2
}

Table MDD_MOVEMENTS {
  MOVEMENT_ID NUMBER [pk]
  CONTAINER_ID_FK NUMBER [ref: > MDD_CONTAINERS.CONTAINER_ID_FK]
  PREVIOUS_LOCATION_ID_FK NUMBER [ref: > MDD_LOCATIONS.PREVIOUS_LOCATION_ID_FK]
  PREVIOUS_LOCATION_NAME VARCHAR2
  PREVIOUS_ENTITY_ID_FK NUMBER [ref: > MDD_NAMES.PREVIOUS_ENTITY_ID_FK]
  MOVEMENT_REASON VARCHAR2
  NEW_LOCATION_ID_FK NUMBER [ref: > MDD_LOCATIONS.NEW_LOCATION_ID_FK]
  NEW_LOCATION_NAME VARCHAR2
  NEW_ENTITY_ID_FK NUMBER [ref: > MDD_NAMES.NEW_ENTITY_ID_FK]
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  TASK_ID_FK NUMBER [ref: > in.TASK_ID_FK]
}

Table MDD_TASKS {
  TASK_ID NUMBER [pk]
  JOB_ID_FK NUMBER [ref: > MDD_JOB.JOB_ID_FK]
  TASK_TYPE_ID NUMBER
  TASK_TYPE VARCHAR2
  TASK_CLIENT VARCHAR2
  TASK_START_DATE DATE
  TASK_END_DATE DATE
  COMPLETE_BY DATE
  TASK_STARTED_BY VARCHAR2
  TASK_COMPLETED_BY VARCHAR2
  TASK_OPERATOR VARCHAR2
  TASK_OPERATOR_FULL VARCHAR2
  CURRENT_OPERATOR_FULL VARCHAR2
  TASK_POSITION NUMBER
  SCHEDULE_AREA NUMBER
  SCHEDULE_AREA_NAME VARCHAR2
  SCHEDULE_AREA_PARENT VARCHAR2
  SCHEDULE_AREA_CODE_FULL VARCHAR2
  SCHEDULE_AREA_FULL VARCHAR2
  CREATED_DATE DATE
  CREATED_BY VARCHAR2
  CREATED_BY_FULL VARCHAR2
  MODIFIED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_BY_FULL VARCHAR2
  TASK_STATUS_ID NUMBER
  TASK_STATUS VARCHAR2
  EQUIPMENT_USED_ID VARCHAR2 [ref: > MDD_TASK_EQUIPMENT.EQUIPMENT_USED_ID]
  TASK_NOTES VARCHAR2
  FULL_NOTES VARCHAR2
  JOB_RAISED NUMBER
  FRIENDLY_NAME VARCHAR2
}

Table MDD_NAA_CARRIER_SHM {
  CARRIER_FORMAT_ID NUMBER [ref: > to.CARRIER_FORMAT_ID]
}

Table MDD_NAA_CONTAINER_SHM {
  CONTAINER_FORMAT_ID NUMBER [ref: > to.CONTAINER_FORMAT_ID]
}

Table MDD_NAMES {
  NAME_ID NUMBER
  ENTITY_ID NUMBER
  FULL_NAME VARCHAR2
  FIRSTNAME VARCHAR2
  SURNAME_OR_COMPANY_NAME VARCHAR2
  CONTACT_ROLE VARCHAR2
  CONTACT_FIRSTNAME VARCHAR2
  CONTACT_SURNAME_COMPANY_NA VARCHAR2
  QUALIFIER VARCHAR2
  DATE_OF_BIRTH DATE
  DATE_OF_DEATH DATE
  OTHER_NAME VARCHAR2
  PREFERRED_NAME VARCHAR2
  NAME_TYPE VARCHAR2
  GENDER VARCHAR2
  DATES VARCHAR2
  ADDRESS VARCHAR2
  CITY VARCHAR2
  STATE VARCHAR2
  POSTCODE VARCHAR2
  PHONE1 VARCHAR2
  PHONE2 VARCHAR2
  FAX VARCHAR2
  EMAIL1 VARCHAR2
  EMAIL2 VARCHAR2
  WEB VARCHAR2
  FILE_NO VARCHAR2
  DELIVER_FAO VARCHAR2
  DELIVERY_CONTACT VARCHAR2
  DELIVERY_ADDRESS VARCHAR2
  DELIVERY_CITY VARCHAR2
  DELIVERY_STATE VARCHAR2
  DELIVERY_POSTCODE VARCHAR2
  CHECKED DATE
  CHECKED_BY VARCHAR2
  DELIVERY_COUNTRY NUMBER
  CULTURAL_BACKGROUND VARCHAR2
  BIOGRAPHY CLOB
  FULL_BIOGRAPHY CLOB
  NOTES CLOB
  CREATED_BY VARCHAR2
  CREATED DATE
  MODIFIED_BY VARCHAR2
  MODIFIED DATE
}

Table MDD_NFSA_MEDIA_USAGE_GROUPS {
  USAGE_ID NUMBER
  USAGE_NAME VARCHAR2
  USAGE_SHORTCODE VARCHAR2
  NFSA_USAGE_GROUP VARCHAR2
}

Table MDD_PACKAGE_MEDIA {
  PACKAGE_ID_FK NUMBER [ref: > Package.PACKAGE_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > Package.MEDIA_ID_FK]
  MEDIA_TYPE CHAR
}

Table MDD_PACKAGE_REQUIREMENTS {
  PACKAGE_REQ_ID NUMBER [pk]
  NAME VARCHAR2
  DESCRIPTION VARCHAR2
  EXTERNAL_ID VARCHAR2
}

Table MDD_POST_EVENT_NOTES {
  ID NUMBER [pk]
  EVENT_NOTES VARCHAR2
  MEDIA_ID_FK NUMBER
}

Table MDD_PRODUCERS {
  TASK_ID_FK NUMBER [ref: > MDD_TASKS.TASK_ID_FK]
  PRODUCER VARCHAR2
  PRODUCER_TITLE VARCHAR2
}

Table MDD_PROGRAM_FORM {
  TITLE_OR_VERSION_ID_FK NUMBER [ref: > version.TITLE_OR_VERSION_ID_FK]
  FORM VARCHAR2
}

Table MDD_PROGRAMS {
  PROGRAM_ID NUMBER
  ITEM_TYPE_ID NUMBER
  SERIES_TITLE VARCHAR2
  EPISODE_NUM NUMBER
  TITLE VARCHAR2
  SERIES_FROM_ABS VARCHAR2
  PRODUCTION_YEAR NUMBER
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
  VERSION_NAME VARCHAR2
  GENRE VARCHAR2
  MEDIUM VARCHAR2
  SUB_MEDIUM VARCHAR2
  FORM VARCHAR2
}

Table MDD_RECORD_LABEL_MEDIA_LINKS {
  RECORD_LABEL_ID_FK NUMBER [ref: > MDD_RECORD_LABELS.RECORD_LABEL_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  RECORD_LABEL_ID NUMBER
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  CARRIER_NO NUMBER
  SIDE_NO NUMBER
  RELEASE_YEAR VARCHAR2
  CATALOGUE_NO_PREFIX VARCHAR2
  CATALOGUE_NO_NUMBER VARCHAR2
  CATALOGUE_NO_SUFFIX VARCHAR2
}

Table MDD_RECORD_LABELS {
  RECORD_LABEL_ID NUMBER [pk]
  RECORD_LABEL_NAME VARCHAR2
  COPYRIGHT_HOLDER_ID_FK NUMBER [ref: > MDD_NAMES.COPYRIGHT_HOLDER_ID_FK]
  COPYRIGHT_HOLDER VARCHAR2
  CREATED_BY NVARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY NVARCHAR2
  MODIFIED_DATE DATE
}

Table MDD_RELATED_NAMES {
  NAME_ID_FK NUMBER [ref: > the.NAME_ID_FK]
  RELATED_NAME_ID NUMBER [pk]
  RELATED_NAME VARCHAR2
  DATES VARCHAR2
}

Table MDD_RESPONSIBILITIES {
  USER_ID VARCHAR2
  FIRST_NAME VARCHAR2
  LAST_NAME VARCHAR2
  ROLE_ID NUMBER
  ROLE_NAME VARCHAR2
  ROLE_DESCRIPTION VARCHAR2
  RESPONSIBILITY VARCHAR2
  RESPONSIBILITY_DESC VARCHAR2
  PERMISSION NUMBER
  ACCESS_TO CHAR
  VIEW CHAR
  MODIFY CHAR
  DELETE CHAR
}

Table MDD_RESTRICTION_REASONS {
  RESTRICTION_REASON_ID NUMBER [pk]
  ACCESS_STATUS_ID_FK NUMBER
  RESTRICTION_REASON VARCHAR2
  DATE_MODIFIED DATE
}

Table MDD_RIGHTS {
  RIGHTS_ID NUMBER [pk]
  RIGHTS_HOLDER NUMBER
  CONTACT VARCHAR2
  AGREEMENT_DATE DATE
  FILE_REF VARCHAR2
  CREATED DATE
  CREATED_BY VARCHAR2
  PERMISSION_TYPE NUMBER
  PERM_TYPE_DESC VARCHAR2
  START_DATE DATE
  END_DATE DATE
  GEOGRAPHICAL_COVERAGE NUMBER
  GEO_COVERAGE_DESC VARCHAR2
  PROJECT_CODE VARCHAR2
  PROJECT_CODE_DESC VARCHAR2
}

Table MDD_SERIES_INDICATORS {
  INDICATOR_ID NUMBER [pk]
  EXTERNAL_ID NUMBER
  INDICATOR_NAME VARCHAR2
  INDICATOR_DESCRIPTION VARCHAR2
}

Table MDD_SERIES_INDICATORS_LNK {
  ID NUMBER [pk]
  INDICATOR_ID_FK NUMBER
  SERIES_ID_FK NUMBER
  IMPORTED NUMBER
  MI_ID_FK NUMBER
  MEDIA_ID_FK NUMBER
}

Table MDD_SPACE_RESERVATION_ITEMS {
  RESERVATION_ID NUMBER [pk]
  LOCATION_ID NUMBER
  ITEM_COUNT NUMBER
  ITEM_TYPE_ID NUMBER
  ITEM_TYPE_NAME VARCHAR2
  FORMAT_ID_FK NUMBER [ref: > MDD_CONTAINERS.FORMAT_ID.FORMAT_ID_FK]
  RESERVATION_LENGTH NUMBER
  RESERVATION_NAME VARCHAR2
  CREATED_DATE DATE
}

Table MDD_SYNONYMS {
  SYNONYM_ID NUMBER [pk]
  NAME_ID_FK NUMBER [ref: > the.NAME_ID_FK]
  SYNONYM_NAME VARCHAR2
  DATES VARCHAR2
  NAME_TYPE VARCHAR2
}

Table MDD_TASK_CONFIG {
  TASK_ID_FK NUMBER
  JOB_ID_FK NUMBER
  ITEM_INDEX NUMBER
  TASK_TYPE_ID NUMBER
  TASK_TYPE VARCHAR2
  MOVE_MODE VARCHAR2
  TOOL_TYPE VARCHAR2
  ARRIVE_BY DATE
  DESPATCH_FROM_LOCATION VARCHAR2
  DESPATCH_TO_LOCATION VARCHAR2
  DESPATCH_TO_CONTACT VARCHAR2
  DESPATCH_TO_CONTACT_FIRST VARCHAR2
  DESPATCH_TO_CONTACT_LAST VARCHAR2
  DESPATCH_TO_ADDRESS VARCHAR2
  DESPATCH_TO_MAIL_CODE VARCHAR2
  DESPATCH_TO_NA VARCHAR2
  DESPATCH_TO_NA_ADDRESS VARCHAR2
  DESPATCH_TO_NA_CITY VARCHAR2
  DESPATCH_TO_NA_STATE VARCHAR2
  DESPATCH_TO_NA_CODE VARCHAR2
  ENTITY_ID_FK NUMBER
  AGENCY_CODE VARCHAR2
  AGENCY_NAME VARCHAR2
  PROFILE_NAME VARCHAR2
}

Table MDD_TASK_EQUIPMENT {
  TASK_ID_FK NUMBER [ref: > associated.TASK_ID_FK]
  JOB_ID_FK NUMBER [ref: > job.JOB_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > associated.MEDIA_ID_FK]
  DEVICE_USED VARCHAR2
  DEVICE_NAME VARCHAR2
  DEVICE_CODE VARCHAR2
  FACILITY_ID VARCHAR2
  FACILITY_NAME VARCHAR2
}

Table MDD_TASK_EQUIPMENT_ID {
  TASK_ID_FK NUMBER
  JOB_ID_FK NUMBER
  MEDIA_ID_FK NUMBER
  LINE_NO NUMBER
  DEVICE_ID VARCHAR2
  FACILITY_ID VARCHAR2
}

Table MDD_TASK_MEDIA {
  TASK_ID_FK NUMBER [ref: > associated.TASK_ID_FK]
  JOB_ID_FK NUMBER [ref: > job.JOB_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > associated.MEDIA_ID_FK]
  CONTAINER_ID_FK NUMBER [ref: > of.CONTAINER_ID_FK]
  MEDIA_CLASS VARCHAR2
  SOURCE NUMBER
  ARRIVE_BY DATE
  DESPATCH_FROM VARCHAR2
  DESPATCH_TO VARCHAR2
  SOURCE_DEST NUMBER
  ITEM_INDEX NUMBER
  TA_REPORT_ID_FK NUMBER
  AGENCY_CODE NUMBER
  AGENCY_NAME VARCHAR2
  MEDIA_STATUS_ID NUMBER
  MEDIA_STATUS VARCHAR2
  DEVICE_PATH VARCHAR2
  DEVICE VARCHAR2
}

Table MDD_TASK_OUTPUT_MEDIA {
  TASK_ID_FK NUMBER [ref: > associated.TASK_ID_FK]
  JOB_ID_FK NUMBER [ref: > job.JOB_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > associated.MEDIA_ID_FK]
  CONTAINER_ID_FK VARCHAR2
  MEDIA_CLASS VARCHAR2
  SOURCE NUMBER
}

Table MDD_TASK_SOURCE_MEDIA {
  TASK_ID_FK NUMBER [ref: > associated.TASK_ID_FK]
  JOB_ID_FK NUMBER [ref: > job.JOB_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > associated.MEDIA_ID_FK]
  CONTAINER_ID_FK NUMBER [ref: > of.CONTAINER_ID_FK]
  MEDIA_CLASS VARCHAR2
  SOURCE NUMBER
  ARRIVE_BY DATE
  DESPATCH_FROM VARCHAR2
  DESPATCH_TO VARCHAR2
  SOURCE_DEST NUMBER
  AGENCY_CODE NUMBER
  AGENCY_NAME VARCHAR2
  MEDIA_STATUS_ID NUMBER
  MEDIA_STATUS VARCHAR2
  DEVICE_PATH VARCHAR2
  DEVICE VARCHAR2
}

Table MDD_TASK_TIMELINE {
  TASK_TIMELINE_ID NUMBER [pk]
  TASK_ID_FK NUMBER [ref: > MDD_TASKS.TASK_ID_FK]
  JOB_ID_FK NUMBER [ref: > MDD_JOB.JOB_ID_FK]
  LOG_ACTION VARCHAR2
  NOTES VARCHAR2
  OPERATOR_ID VARCHAR2
  TIMESTAMP DATE
}

Table MDD_TASK_VIDEO_MEASUREMENTS {
  MEDIA_ID_FK NUMBER [ref: > associated.MEDIA_ID_FK]
  TASK_ID_FK NUMBER [ref: > associated.TASK_ID_FK]
  VITC VARCHAR2
  DIGITAL_ERR VARCHAR2
  LTC VARCHAR2
  DIGITAL_BLANKING VARCHAR2
  DIGITAL_CH VARCHAR2
  PB_PHASE VARCHAR2
  BARS_REF VARCHAR2
  AUD_REF VARCHAR2
}

Table MDD_TASKS_OLD {
  TASK_ID NUMBER
  PRESET VARCHAR2
  COMPLETED_DATE DATE
  DAY VARCHAR2
  MONTH VARCHAR2
  YEAR VARCHAR2
  TASK_TYPE NUMBER
}

Table MDD_TITLE_GENRE {
  TITLE_ID_FK NUMBER
  GENRE_ID NUMBER [pk]
  GENRE VARCHAR2
}

Table MDD_TITLES {
  TITLE_ID NUMBER [pk]
  TITLE_TYPE VARCHAR2
  PARENT_SERIES_ID_FK NUMBER
  SERIES_TITLE VARCHAR2
  PARENT_SEASON_ID_FK NUMBER
  SEASON VARCHAR2
  TITLE VARCHAR2
  ORIGINAL_TITLE VARCHAR2
  ITEM_TYPE_ID NUMBER
  EPISODE_NUM NUMBER
  PRODUCTION_YEAR NUMBER
  SERIES_TYPE NUMBER
  PROGRAM_ID1 VARCHAR2
  PROGRAM_ID2 VARCHAR2
  SERIES_ID1 VARCHAR2
  SERIES_ID2 VARCHAR2
  VERSION_ID1 VARCHAR2
  VERSION_ID2 VARCHAR2
  EXPECTED_DURATION NUMBER
  EXPECTED_ASPECT_RATIO NUMBER
  OWNERS VARCHAR2
  SLOT_DURATION NUMBER
  RUN_TIME_DURATION NUMBER
  COPYRIGHT_STATUS NUMBER
  COPYRIGHT_STATUS_DESC NVARCHAR2
  CULTURAL_STATUS VARCHAR2
  CULTURAL_STATUS_DESC VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
  MEDIUM_ID_FK NUMBER
  MEDIUM VARCHAR2
  SUB_MEDIUM_ID_FK NUMBER
  SUB_MEDIUM VARCHAR2
  ATTACHMENT_FILENAMES CLOB
  URL_REFERENCES CLOB
  DELETED NUMBER
  DELETED_BY VARCHAR2
  DELETED_DATE DATE
  TITLE_PARENTAL_RATING VARCHAR2
  TITLE_PARENTAL_SUBRATING VARCHAR2
}

Table MDD_TRANSMISSION_SCHEDULE {
  SCHEDULE_ID NUMBER [pk]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  MEDIA_ID_FK NUMBER [ref: > MDD_MEDIA.MEDIA_ID_FK]
  NETWORK VARCHAR2
  TRANSMISSION_DATE DATE
  TRANSMISSION_START DATE
  TRANSMISSION_END DATE
  TRANSMISSION_SERIES_TITLE VARCHAR2
  TRANSMISSION_TITLE VARCHAR2
  PRODUCT_NUMBER VARCHAR2
  DURATION_SECONDS NUMBER
  QC_STATUS VARCHAR2
}

Table MDD_USER_ACCESS_GROUPS {
  USER_ID VARCHAR2
  USER_NAME VARCHAR2
  STATUS VARCHAR2
  ACCESS_GROUP VARCHAR2
  CREATED DATE
  IS_IMFX VARCHAR2
}

Table MDD_USER_SCHEDULE_RIGHTS {
  USER_ID VARCHAR2
  SCHEDULE_RIGHTS_ID VARCHAR2
  SCHEDULE_RIGHTS VARCHAR2
}

Table MDD_USERS {
  USER_ID VARCHAR2
  FULL_NAME VARCHAR2
  TITLE VARCHAR2
  PHONE VARCHAR2
  EMAIL VARCHAR2
  EXPIRYDATE DATE
  DEPARTMENT VARCHAR2
  AREA_SHORT_CODE VARCHAR2
  AREA VARCHAR2
  DBA_MODE VARCHAR2
  IS_DISABLED VARCHAR2
  LAST_MFX_LOGIN_DATE DATE
  LAST_IMFX_LOGIN_DATE DATE
}

Table MDD_VERSION_COUNTRY {
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  COUNTRY VARCHAR2
}

Table MDD_VERSION_LANGUAGE {
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  LANGUAGE VARCHAR2
  ROLE VARCHAR2
}

Table MDD_VERSION_MATRIX_NUMBER {
  MAT_NUM_ID NUMBER [pk]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  MATRIX_PREFIX VARCHAR2
  MATRIX_NUMBER VARCHAR2
  MATRIX_SUFFIX VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
}

Table MDD_VERSION_PLACE {
  VERSION_ID_FK NUMBER [pk]
  VERSION_ID1_FK VARCHAR2
  PLACE VARCHAR2
  PLACE_TYPE VARCHAR2
}

Table MDD_VERSION_PRODUCTION_DATES {
  PROD_DATE_ID NUMBER [pk]
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  DATE_TYPE_ID NUMBER
  DATE_TYPE VARCHAR2
  DATE_FROM DATE
  DATE_TO DATE
  FROM_DAY NUMBER
  FROM_MONTH NUMBER
  FROM_YEAR NUMBER
  TO_DAY NUMBER
  TO_MONTH NUMBER
  TO_YEAR NUMBER
  CIRCA NUMBER
  NOTES VARCHAR2
  CREATED_BY NVARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY NVARCHAR2
  MODIFIED_DATE DATE
}

Table MDD_VERSION_RELATED {
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  RELATED_VERSION_ID_FK NUMBER [ref: > Key.RELATED_VERSION_ID_FK]
  RELATED_VERSION_ID1 VARCHAR2
  RELATED_VERSION_TITLE VARCHAR2
  RELATED_VERSION_NAME VARCHAR2
}

Table MDD_VERSION_RIGHTS {
  RIGHTS_ID NUMBER [pk]
  RIGHTS_HOLDER NUMBER
  CONTACT VARCHAR2
  AGREEMENT_DATE DATE
  FILE_REF VARCHAR2
  CREATED DATE
  CREATED_BY VARCHAR2
  VERSION_ID NUMBER
  PERMISSION_TYPE NUMBER
  PERM_TYPE_DESC VARCHAR2
  START_DATE DATE
  END_DATE DATE
  GEOGRAPHICAL_COVERAGE NUMBER
  GEO_COVERAGE_DESC VARCHAR2
  PROJECT_CODE VARCHAR2
  PROJECT_CODE_DESC VARCHAR2
}

Table MDD_VERSION_SEGMENTS {
  VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.VERSION_ID_FK]
  SEGMENT_NO NUMBER
  PART_NO NUMBER
  SEGMENT_TYPE NUMBER
  SEGMENT_TYPE_DESC NVARCHAR2
  SEGMENT_TITLE VARCHAR2
  SOM_FRAMES NUMBER
  SOM VARCHAR2
  EOM_FRAMES NUMBER
  EOM VARCHAR2
  DURATION_FRAMES NUMBER
  DUR VARCHAR2 [ref: > timecode.DUR]
  USE_IN_DUR_CALC NUMBER
  TX_PART NUMBER
}

Table MDD_VERSIONS {
  VERSION_ID NUMBER [pk]
  ITEM_TYPE_ID NUMBER [ref: > MDD_MEDIA_ITEM_TYPES.ITEM_TYPE_ID]
  TITLE_ID_FK NUMBER [ref: > MDD_TITLES.TITLE_ID_FK]
  PARENT_VERSION_ID_FK NUMBER [ref: > MDD_VERSIONS.PARENT_VERSION_ID_FK]
  MASTER_VERSION_ID_FK NUMBER
  VERSION_TYPE CHAR
  VERSION_TITLE VARCHAR2
  VERSION_SERIES_TITLE VARCHAR2
  VERSION_SERIES_NAME VARCHAR2
  VERSION_EPISODE VARCHAR2
  EPISODE_NUM NUMBER
  VERSION_ID1 VARCHAR2
  VERSION_ID2 VARCHAR2
  VERSION_PROGRAM_ID1 VARCHAR2
  VERSION_PROGRAM_ID2 VARCHAR2
  HOUSE_NUMBER VARCHAR2
  VERSION_NAME VARCHAR2
  EXPECTED_DURATION NUMBER
  SLOT_DURATION NUMBER
  OWNERS VARCHAR2
  STATUS_ID NUMBER
  STATUS NVARCHAR2
  EXPECTED_FORMAT NUMBER
  ASPECT_RATIO NUMBER
  ASPECT_RATIO_NAME VARCHAR2
  TV_STD NVARCHAR2
  NEXT_TX_DATE DATE
  ITV_CAT VARCHAR2
  ITV_TYPE NUMBER
  REF_CODE VARCHAR2
  SUB_MEDIUM VARCHAR2
  CREATED_BY VARCHAR2
  CREATED_DT DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DT DATE
  COPYRIGHT_STATUS NUMBER
  COPYRIGHT_STATUS_DESC NVARCHAR2
  CULTURAL_STATUS_ID VARCHAR2
  CULTURAL_STATUS_DESC VARCHAR2
  ALTERNATIVE_TITLES VARCHAR2
  ATTACHMENT_FILENAMES CLOB
  URL_REFERENCES CLOB
  PRODUCTION_PLACE_TYPE VARCHAR2
  PRODUCTION_PLACE VARCHAR2
  PRODUCTION_COLOUR_ID NUMBER
  PRODUCTION_COLOUR NVARCHAR2
  PRODUCTION_AUDIO_ID NUMBER
  PRODUCTION_AUDIO NVARCHAR2
  NOTES VARCHAR2
  DELETED NUMBER
  DELETED_BY VARCHAR2
  DELETED_DATE DATE
  PARENTAL_RATING VARCHAR2
  PARENTAL_SUBRATING VARCHAR2
  VERSION_GUID VARCHAR2
}

Table MDD_XML_METADATA {
  XML_ID NUMBER [pk]
  LINKING_ID_FK NUMBER [ref: > info.LINKING_ID_FK]
  XML_LINK_TYPE VARCHAR2
  SCHEMA_TYPE NUMBER
  XML_TYPE VARCHAR2
  SCHEMA_NAME VARCHAR2
  DATA_TYPE NUMBER
  CREATED_BY VARCHAR2
  CREATED_DATE DATE
  MODIFIED_BY VARCHAR2
  MODIFIED_DATE DATE
  XML_DATA XMLTYPE
  OWN_ID NUMBER
  MEDIA_ID_FK NUMBER
  VERSION_ID_FK NUMBER
}

